In [1]:
print("hello world!")

hello world!


In [ ]:
num =20

In [2]:
print(num)

NameError: name 'num' is not defined

In [3]:
num = 20

In [4]:
print(num)

20


In [5]:
print("bharath")

bharath


In [6]:
import numpy as np

In [11]:
def function():
    l1=[10,20,30,40,50]
    print(l1)
    print(f"type={type(l1)}")
    print(f"l[2]={l1[2]}")

In [12]:
function()

[10, 20, 30, 40, 50]
type=<class 'list'>
l[2]=30


In [13]:
def function2():
    l1=[10,20,30,40,50]
    print(l1)
    print(f"type={type(l1)}")
    print(f"l[2]={l1[2]}")
    print(f"l1[2]={type(l1[2])}")

In [14]:
function2()


[10, 20, 30, 40, 50]
type=<class 'list'>
l[2]=30
l1[2]=<class 'int'>


In [15]:
def function3():
    np_arr=np.array([10,20,30,40])
    print(np_arr)
    print(f"np_arr={type(np_arr)}")

In [16]:
function3()

[10 20 30 40]
np_arr=<class 'numpy.ndarray'>


In [24]:
def function4():
    np_arr=np.array([10,20,30,40])
    print(np_arr)
    print(f"np_arr={type(np_arr)}")
    print(f"dtype={np_arr.dtype}")
    print(f"item size={np_arr.itemsize}")
    print(f"size ={np_arr.size}")
    print(f"NDIM={np_arr.ndim}")
    print(f"NBYTES={np_arr.nbytes}")

In [25]:
function4()

[10 20 30 40]
np_arr=<class 'numpy.ndarray'>
dtype=int64
item size=8
size =4
NDIM=1
NBYTES=32


In [29]:
def function5(np_arr):
   
    print(np_arr)
    print(f"np_arr={type(np_arr)}")
    print(f"dtype={np_arr.dtype}")
    print(f"item size={np_arr.itemsize}")
    print(f"size ={np_arr.size}")
    print(f"NDIM={np_arr.ndim}")
    print(f"NBYTES={np_arr.nbytes}")

In [27]:
arr=np.array([10,20,30,40])
function5(arr)

[10 20 30 40]
np_arr=<class 'numpy.ndarray'>
dtype=int64
item size=8
size =4
NDIM=1
NBYTES=32


In [32]:
arr2=np.array([10,20,30,40],dtype=np.int16)
function5(arr2)

[10 20 30 40]
np_arr=<class 'numpy.ndarray'>
dtype=int16
item size=2
size =4
NDIM=1
NBYTES=8


In [33]:
arr3=np.array([10,20,30,40],dtype=np.int64)
function5(arr3)

[10 20 30 40]
np_arr=<class 'numpy.ndarray'>
dtype=int64
item size=8
size =4
NDIM=1
NBYTES=32


In [36]:
arr4=np.array([2.740,2.34,3.24])
function5(arr4)


[2.74 2.34 3.24]
np_arr=<class 'numpy.ndarray'>
dtype=float64
item size=8
size =3
NDIM=1
NBYTES=24


In [45]:
arr5=np.array([2.70,6.80,7.80],dtype=np.float16)
function5(arr5)

[2.7 6.8 7.8]
np_arr=<class 'numpy.ndarray'>
dtype=float16
item size=2
size =3
NDIM=1
NBYTES=6


In [54]:
n5 = np.array(["C","C++","Python","Java"],dtype=np.uintc)
function5(n5)

ValueError: invalid literal for int() with base 10: 'C'

In [53]:
#scliceing indexing